version: '3.7'
networks:
  getinc-net:
    name: ${DOCKER_NETWORK}
    driver: bridge
services:
  db:
    image: db
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: db
    build:
      context: ./dockers/db
      target: db
    ports:
      - 5432:5432
    networks:
      - getinc-net
    environment:
      - TZ=GMT+2
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata2

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - getinc-net
    depends_on:
      - db
      
  python_api:
    image: python:3.10
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - getinc-net
    depends_on:
      - db
    environment:
      - PY_API_HOST=${PY_API_HOST}
      - PY_WEB_HOST=${PY_WEB_HOST}
      - PY_EMAIL_FROM=${PY_EMAIL_FROM}
      - PY_EMAIL_USER=${PY_EMAIL_USER}
      - PY_EMAIL_PASSWORD=${PY_EMAIL_PASSWORD}
      - PY_EMAIL_HOST=${PY_EMAIL_HOST}
      - PY_EMAIL_PORT=${PY_EMAIL_PORT}
      - PY_DB_USER=${PY_DB_USER}
      - PY_DB_PASSWORD=${PY_DB_PASSWORD}
      - PY_DB_HOST=${PY_DB_HOST}
      - PY_DB_PORT=${PY_DB_PORT}
      - PY_DB_DATABASE=${PY_DB_DATABASE}
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000


